import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { counterActions } from "../store/slice";

export default function Home() {
  const dispatch = useDispatch();
  const { count } = useSelector((state) => state.counter); // this is one way to get the redux state

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* counter example to use redux state below */}
        <div className="flex justify-center">
          <button
            className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white"
            onClick={() => {
              // dispatch(counterActions.setCount(count + 1));   can be used like this also to change redux state
              dispatch(counterActions.increment()); // this is proper way to use reducers to change redux state
            }}
          >
            count: {count}
          </button>
        </div>
      </main>
    </>
  );
}
